# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=100)),
                ('date_sent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ID', models.IntegerField()),
                ('reciver_ID', models.IntegerField()),
            ],
        ),
    ]
