# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_state', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('lender_rating_of_borrower', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrower_rating_of_lender', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.IntegerField()),
                ('lender_ID', models.IntegerField()),
                ('borrower_ID', models.IntegerField()),
            ],
        ),
    ]
