# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_listed', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(null=True, upload_to='itemImages')),
                ('category_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anyWares.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Calandar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_date', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anyWares.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=100)),
                ('date_sent', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('credit_card', models.CharField(max_length=20)),
                ('card_experation_month', models.CharField(max_length=20)),
                ('card_experation_year', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=50)),
                ('billing_city', models.CharField(max_length=20)),
                ('billing_state', models.CharField(max_length=20)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('billing_country', models.CharField(max_length=20)),
                ('lending_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrowing_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DateStarted', models.DateTimeField(auto_now=True)),
                ('LastLogin', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_state', models.CharField(max_length=20)),
                ('lender_rating_of_borrower', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrower_rating_of_lender', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrower_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='anyWares.Profile')),
                ('item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anyWares.Item')),
                ('lender_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='anyWares.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Calandar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(auto_now=True)),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anyWares.Rental')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reciver_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='anyWares.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='anyWares.Profile'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anyWares.Profile'),
        ),
    ]
