# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.DurationField()),
                ('picture', models.FileField(upload_to='')),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anywares.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=100)),
                ('date_sent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_state', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('lender_rating_of_borrower', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrower_rating_of_lender', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('credit_card', models.CharField(max_length=20)),
                ('card_experation_month', models.CharField(max_length=20)),
                ('card_experation_year', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=50)),
                ('billing_city', models.CharField(max_length=20)),
                ('billing_state', models.CharField(max_length=20)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('billing_country', models.CharField(max_length=20)),
                ('lending_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrowing_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DateStarted', models.DateTimeField()),
                ('LastLogin', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='borrower_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='anywares.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anywares.Item'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lender_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='anywares.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciver_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='anywares.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='anywares.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anywares.User'),
        ),
    ]
