# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='borrowing_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lending_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
