# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0002_auto_20171129_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
