# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anywares', '0002_auto_20171115_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_Calandar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField()),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anywares.Rental')),
            ],
        ),
    ]
