# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 18:37
from __future__ import unicode_literals

import anyWares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0002_auto_20171122_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(upload_to=anyWares.models.Item.generate_upload_path),
        ),
    ]
