# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anywares', '0003_rental_calandar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='availability',
        ),
    ]
