# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0003_auto_20171201_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
