# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0004_remove_category_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='borrowing_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_experation_month',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_experation_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lending_rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='200x200.png', upload_to='itemImages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
