# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anywares', '0004_remove_item_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Calandar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_date', models.DateTimeField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anywares.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='start_date',
        ),
    ]
