# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anywares', '0005_auto_20171115_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('credit_card', models.CharField(max_length=20)),
                ('card_experation_month', models.CharField(max_length=20)),
                ('card_experation_year', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=50)),
                ('billing_city', models.CharField(max_length=20)),
                ('billing_state', models.CharField(max_length=20)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('billing_country', models.CharField(max_length=20)),
                ('lending_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrowing_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DateStarted', models.DateTimeField()),
                ('LastLogin', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='owner_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anywares.User_Profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciver_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='anywares.User_Profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='anywares.User_Profile'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='borrower_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='anywares.User_Profile'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lender_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='anywares.User_Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
