# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 19:33
from __future__ import unicode_literals

import anyWares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0005_auto_20171124_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(null=True, upload_to=anyWares.models.Item.generate_upload_path),
        ),
    ]
