# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0006_auto_20171124_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
