# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anywares', '0006_auto_20171115_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_name',
        ),
    ]
