# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anywares', '0008_auto_20171115_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_listed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
