# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0009_auto_20171124_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fileReference',
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(null=True, upload_to='anyWares/static/anyWares/media'),
        ),
    ]
