# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 21:32
from __future__ import unicode_literals

import anyWares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyWares', '0012_auto_20171125_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to=anyWares.models.Item.generate_upload_path),
        ),
    ]
